In [1]:
import pandas as pd
import numpy as np
import sys, os
from IPython.display import display

In [33]:
# Declare all variables as strings. Spaces must be replaced with '+', i.e., change 'John Smith' to 'John+Smith'.
# Define the lat, long of the location and the year
lat, lon, year = 35.382200773829396, -120.06015971196985, 2010
# You must request an NSRDB api key from the link above
api_key = '0gXizoqhe4LhjZl5LfStJ1dgixfiGeEznNjjwqhr'
# Set the attributes to extract (e.g., dhi, ghi, etc.), separated by commas.
attributes = 'ghi,dhi,dni,wind_speed,air_temperature,solar_zenith_angle'
# Choose year of data
year = '2019'
# Set leap year to true or false. True will return leap day data if present, false will not.
leap_year = 'false'
# Set time interval in minutes, i.e., '30' is half hour intervals. Valid intervals are 30 & 60.
interval = '60'
# Specify Coordinated Universal Time (UTC), 'true' will use UTC, 'false' will use the local time zone of the data.
# NOTE: In order to use the NSRDB data in SAM, you must specify UTC as 'false'. SAM requires the data to be in the
# local time zone.
utc = 'false'
# Your full name, use '+' instead of spaces.
your_name = 'John+Smith'
# Your reason for using the NSRDB.
reason_for_us'beta+testing'
# Your affiliation
your_affiliation = 'my+institution'
# Your email address
your_email = 'user@nrel.gov'
# Please join our mailing list so we can keep you up-to-date on new developments.
mailing_list = 'true'

# Declare url string
url = 'https://developer.nrel.gov/api/nsrdb/v2/solar/psm3-download.csv?wkt=POINT({lon}%20{lat})&names={year}&leap_day={leap}&interval={interval}&utc={utc}&full_name={name}&email={email}&affiliation={affiliation}&mailing_list={mailing_list}&reason={reason}&api_key={api}&attributes={attr}'.format(year=year, lat=lat, lon=lon, leap=leap_year, interval=interval, utc=utc, name=your_name, email=your_email, mailing_list=mailing_list, affiliation=your_affiliation, reason=reason_for_use, api=api_key, attr=attributes)
print(url)
# Return just the first 2 lines to get metadata:
info = pd.read_csv(url, nrows=365*24)
# See metadata for specified properties, e.g., timezone and elevation
timezone, elevation = info['Local Time Zone'], info['Elevation']

https://developer.nrel.gov/api/nsrdb/v2/solar/psm3-download.csv?wkt=POINT(-120.06015971196985%2035.382200773829396)&names=2019&leap_day=false&interval=60&utc=false&full_name=John+Smith&email=user@nrel.gov&affiliation=my+institution&mailing_list=true&reason=beta+testing&api_key=0gXizoqhe4LhjZl5LfStJ1dgixfiGeEznNjjwqhr&attributes=ghi,dhi,dni,wind_speed,air_temperature,solar_zenith_angle

In [34]:
info

,Source,Location ID,City,State,Country,Latitude,Longitude,Time Zone,Elevation,Local Time Zone,...,Cloud Type 11,Cloud Type 12,Fill Flag 0,Fill Flag 1,Fill Flag 2,Fill Flag 3,Fill Flag 4,Fill Flag 5,Surface Albedo Units,Version
0,NSRDB,96636,-,-,-,35.37,-120.06,-8,620,-8,...,Dust,Smoke,NaN,Missing Image,Low Irradiance,Exceeds Clearsky,Missing CLoud Properties,Rayleigh Violation,NaN,3.1.1
1,Year,Month,Day,Hour,Minute,GHI,DHI,DNI,Wind Speed,Temperature,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019,1,1,0,30,0,0,0,0.5,0.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019,1,1,1,30,0,0,0,0.5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019,1,1,2,30,0,0,0,0.5,-0.30000000000000004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2019,12,31,17,30,0,0,0,1.6,3.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8756,2019,12,31,18,30,0,0,0,1.7000000000000002,2.8000000000000003,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8757,2019,12,31,19,30,0,0,0,1.6,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8758,2019,12,31,20,30,0,0,0,1.5,1.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8759,2019,12,31,21,30,0,0,0,1.3,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
info.to_csv('Topaz Solar Farm_2019.csv')